# Generated by Django 4.2 on 2023-05-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_rename_serviceid_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
