# Generated by Django 4.2 on 2023-05-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_bookinguser_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='grandtotal',
        ),
    ]
